# The Site Configuration

# Import the theme
# theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
# baseurl: ''

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en


# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Kolkata

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Ashish Yadav                          # the main title

tagline: Software Engineer (Full Stack)   # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  I am a passionate developer with a deep understanding of web technologies, cloud computing, and microservices architecture. I enjoy working on challenging projects and learning new technologies to stay ahead in this rapidly evolving field.
# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: ''

github:
  username: AshishAYadav             # change to your github username

twitter:
  username: AshishAYadav            # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Ashish Yadav
  email: ashishyadav.tcet@gmail.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/AshishAYadav      # change to your twitter homepage
    - https://github.com/AshishAYadav       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/AshishAYadav

# google_site_verification:               # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# google_analytics:
#   id:                 # fill in your Google Analytics ID
#   # Google Analytics pageviews report settings
#   pv:
#     proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
#     cache_path:       # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:    [dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
# img_cdn: 'https://chirpy-img.netlify.app'

# the avatar on sidebar, support local or CORS resources
avatar: 'https://avatars.githubusercontent.com/u/25642690'